// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "cnn_xcel.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic cnn_xcel::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic cnn_xcel::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<18> cnn_xcel::ap_ST_fsm_state1 = "1";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state2 = "10";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state3 = "100";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state4 = "1000";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state5 = "10000";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state6 = "100000";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state7 = "1000000";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state8 = "10000000";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state9 = "100000000";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state10 = "1000000000";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state11 = "10000000000";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state12 = "100000000000";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<18> cnn_xcel::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<32> cnn_xcel::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> cnn_xcel::ap_const_lv32_1 = "1";
const sc_lv<1> cnn_xcel::ap_const_lv1_0 = "0";
const sc_lv<32> cnn_xcel::ap_const_lv32_7 = "111";
const sc_lv<32> cnn_xcel::ap_const_lv32_8 = "1000";
const sc_lv<32> cnn_xcel::ap_const_lv32_9 = "1001";
const sc_lv<32> cnn_xcel::ap_const_lv32_A = "1010";
const sc_lv<32> cnn_xcel::ap_const_lv32_10 = "10000";
const sc_lv<6> cnn_xcel::ap_const_lv6_0 = "000000";
const sc_lv<13> cnn_xcel::ap_const_lv13_0 = "0000000000000";
const sc_lv<10> cnn_xcel::ap_const_lv10_0 = "0000000000";
const sc_lv<32> cnn_xcel::ap_const_lv32_6 = "110";
const sc_lv<32> cnn_xcel::ap_const_lv32_11 = "10001";
const sc_lv<1> cnn_xcel::ap_const_lv1_1 = "1";
const sc_lv<32> cnn_xcel::ap_const_lv32_2 = "10";
const sc_lv<32> cnn_xcel::ap_const_lv32_3 = "11";
const sc_lv<32> cnn_xcel::ap_const_lv32_4 = "100";
const sc_lv<32> cnn_xcel::ap_const_lv32_5 = "101";
const sc_lv<3> cnn_xcel::ap_const_lv3_1 = "1";
const sc_lv<3> cnn_xcel::ap_const_lv3_0 = "000";
const sc_lv<32> cnn_xcel::ap_const_lv32_B = "1011";
const sc_lv<6> cnn_xcel::ap_const_lv6_31 = "110001";
const sc_lv<6> cnn_xcel::ap_const_lv6_1 = "1";
const sc_lv<12> cnn_xcel::ap_const_lv12_0 = "000000000000";
const sc_lv<13> cnn_xcel::ap_const_lv13_56 = "1010110";
const sc_lv<32> cnn_xcel::ap_const_lv32_C = "1100";
const sc_lv<6> cnn_xcel::ap_const_lv6_3 = "11";
const sc_lv<10> cnn_xcel::ap_const_lv10_240 = "1001000000";
const sc_lv<10> cnn_xcel::ap_const_lv10_1 = "1";
const sc_lv<32> cnn_xcel::ap_const_lv32_D = "1101";
const sc_lv<14> cnn_xcel::ap_const_lv14_0 = "00000000000000";
const sc_lv<18> cnn_xcel::ap_const_lv18_3FFFF = "111111111111111111";
const sc_lv<32> cnn_xcel::ap_const_lv32_1F = "11111";
const sc_lv<31> cnn_xcel::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<32> cnn_xcel::ap_const_lv32_1E = "11110";
const sc_lv<26> cnn_xcel::ap_const_lv26_0 = "00000000000000000000000000";
const sc_lv<4> cnn_xcel::ap_const_lv4_1 = "1";
const sc_lv<32> cnn_xcel::ap_const_lv32_17 = "10111";
const sc_lv<8> cnn_xcel::ap_const_lv8_9E = "10011110";
const sc_lv<8> cnn_xcel::ap_const_lv8_74 = "1110100";
const sc_lv<8> cnn_xcel::ap_const_lv8_73 = "1110011";
const bool cnn_xcel::ap_const_boolean_1 = true;

cnn_xcel::cnn_xcel(sc_module_name name) : sc_module(name), mVcdFile(0) {
    mem_conv1_0_V_U = new cnn_xcel_mem_convqcK("mem_conv1_0_V_U");
    mem_conv1_0_V_U->clk(ap_clk);
    mem_conv1_0_V_U->reset(ap_rst);
    mem_conv1_0_V_U->address0(mem_conv1_0_V_address0);
    mem_conv1_0_V_U->ce0(mem_conv1_0_V_ce0);
    mem_conv1_0_V_U->we0(mem_conv1_0_V_we0);
    mem_conv1_0_V_U->d0(tmp_s_fu_320_p3);
    mem_conv1_0_V_U->q0(mem_conv1_0_V_q0);
    mem_conv1_0_V_U->address1(grp_perform_conv_1_fu_258_input_V_address1);
    mem_conv1_0_V_U->ce1(mem_conv1_0_V_ce1);
    mem_conv1_0_V_U->q1(mem_conv1_0_V_q1);
    mem_conv1_1_V_U = new cnn_xcel_mem_convqcK("mem_conv1_1_V_U");
    mem_conv1_1_V_U->clk(ap_clk);
    mem_conv1_1_V_U->reset(ap_rst);
    mem_conv1_1_V_U->address0(mem_conv1_1_V_address0);
    mem_conv1_1_V_U->ce0(mem_conv1_1_V_ce0);
    mem_conv1_1_V_U->we0(mem_conv1_1_V_we0);
    mem_conv1_1_V_U->d0(tmp_s_fu_320_p3);
    mem_conv1_1_V_U->q0(mem_conv1_1_V_q0);
    mem_conv1_1_V_U->address1(grp_perform_conv_1_fu_258_input_V1_address1);
    mem_conv1_1_V_U->ce1(mem_conv1_1_V_ce1);
    mem_conv1_1_V_U->q1(mem_conv1_1_V_q1);
    mem_conv1_2_V_U = new cnn_xcel_mem_convsc4("mem_conv1_2_V_U");
    mem_conv1_2_V_U->clk(ap_clk);
    mem_conv1_2_V_U->reset(ap_rst);
    mem_conv1_2_V_U->address0(mem_conv1_2_V_address0);
    mem_conv1_2_V_U->ce0(mem_conv1_2_V_ce0);
    mem_conv1_2_V_U->we0(mem_conv1_2_V_we0);
    mem_conv1_2_V_U->d0(tmp_s_fu_320_p3);
    mem_conv1_2_V_U->q0(mem_conv1_2_V_q0);
    mem_conv1_2_V_U->address1(grp_perform_conv_1_fu_258_input_V2_address1);
    mem_conv1_2_V_U->ce1(mem_conv1_2_V_ce1);
    mem_conv1_2_V_U->q1(mem_conv1_2_V_q1);
    mem_conv2_0_V_U = new cnn_xcel_mem_convtde("mem_conv2_0_V_U");
    mem_conv2_0_V_U->clk(ap_clk);
    mem_conv2_0_V_U->reset(ap_rst);
    mem_conv2_0_V_U->address0(mem_conv2_0_V_address0);
    mem_conv2_0_V_U->ce0(mem_conv2_0_V_ce0);
    mem_conv2_0_V_U->we0(mem_conv2_0_V_we0);
    mem_conv2_0_V_U->d0(grp_perform_conv_1_fu_258_output_V_d0);
    mem_conv2_0_V_U->q0(mem_conv2_0_V_q0);
    mem_conv2_0_V_U->address1(grp_perform_conv_fu_274_input_0_V_address1);
    mem_conv2_0_V_U->ce1(mem_conv2_0_V_ce1);
    mem_conv2_0_V_U->q1(mem_conv2_0_V_q1);
    mem_conv2_1_V_U = new cnn_xcel_mem_convtde("mem_conv2_1_V_U");
    mem_conv2_1_V_U->clk(ap_clk);
    mem_conv2_1_V_U->reset(ap_rst);
    mem_conv2_1_V_U->address0(mem_conv2_1_V_address0);
    mem_conv2_1_V_U->ce0(mem_conv2_1_V_ce0);
    mem_conv2_1_V_U->we0(mem_conv2_1_V_we0);
    mem_conv2_1_V_U->d0(grp_perform_conv_1_fu_258_output_V3_d0);
    mem_conv2_1_V_U->q0(mem_conv2_1_V_q0);
    mem_conv2_1_V_U->address1(grp_perform_conv_fu_274_input_1_V_address1);
    mem_conv2_1_V_U->ce1(mem_conv2_1_V_ce1);
    mem_conv2_1_V_U->q1(mem_conv2_1_V_q1);
    mem_conv2_2_V_U = new cnn_xcel_mem_convtde("mem_conv2_2_V_U");
    mem_conv2_2_V_U->clk(ap_clk);
    mem_conv2_2_V_U->reset(ap_rst);
    mem_conv2_2_V_U->address0(mem_conv2_2_V_address0);
    mem_conv2_2_V_U->ce0(mem_conv2_2_V_ce0);
    mem_conv2_2_V_U->we0(mem_conv2_2_V_we0);
    mem_conv2_2_V_U->d0(grp_perform_conv_1_fu_258_output_V4_d0);
    mem_conv2_2_V_U->q0(mem_conv2_2_V_q0);
    mem_conv2_2_V_U->address1(grp_perform_conv_fu_274_input_2_V_address1);
    mem_conv2_2_V_U->ce1(mem_conv2_2_V_ce1);
    mem_conv2_2_V_U->q1(mem_conv2_2_V_q1);
    mem_conv2_3_V_U = new cnn_xcel_mem_convtde("mem_conv2_3_V_U");
    mem_conv2_3_V_U->clk(ap_clk);
    mem_conv2_3_V_U->reset(ap_rst);
    mem_conv2_3_V_U->address0(mem_conv2_3_V_address0);
    mem_conv2_3_V_U->ce0(mem_conv2_3_V_ce0);
    mem_conv2_3_V_U->we0(mem_conv2_3_V_we0);
    mem_conv2_3_V_U->d0(grp_perform_conv_1_fu_258_output_V5_d0);
    mem_conv2_3_V_U->q0(mem_conv2_3_V_q0);
    mem_conv2_3_V_U->address1(grp_perform_conv_fu_274_input_3_V_address1);
    mem_conv2_3_V_U->ce1(mem_conv2_3_V_ce1);
    mem_conv2_3_V_U->q1(mem_conv2_3_V_q1);
    mem_conv2_4_V_U = new cnn_xcel_mem_convtde("mem_conv2_4_V_U");
    mem_conv2_4_V_U->clk(ap_clk);
    mem_conv2_4_V_U->reset(ap_rst);
    mem_conv2_4_V_U->address0(mem_conv2_4_V_address0);
    mem_conv2_4_V_U->ce0(mem_conv2_4_V_ce0);
    mem_conv2_4_V_U->we0(mem_conv2_4_V_we0);
    mem_conv2_4_V_U->d0(grp_perform_conv_1_fu_258_output_V6_d0);
    mem_conv2_4_V_U->q0(mem_conv2_4_V_q0);
    mem_conv2_4_V_U->address1(grp_perform_conv_fu_274_input_4_V_address1);
    mem_conv2_4_V_U->ce1(mem_conv2_4_V_ce1);
    mem_conv2_4_V_U->q1(mem_conv2_4_V_q1);
    mem_conv3_V_U = new cnn_xcel_mem_convyd2("mem_conv3_V_U");
    mem_conv3_V_U->clk(ap_clk);
    mem_conv3_V_U->reset(ap_rst);
    mem_conv3_V_U->address0(mem_conv3_V_address0);
    mem_conv3_V_U->ce0(mem_conv3_V_ce0);
    mem_conv3_V_U->we0(mem_conv3_V_we0);
    mem_conv3_V_U->d0(grp_perform_conv_fu_274_output_V_d0);
    mem_conv3_V_U->q0(mem_conv3_V_q0);
    reshape_output_V_U = new cnn_xcel_mem_convyd2("reshape_output_V_U");
    reshape_output_V_U->clk(ap_clk);
    reshape_output_V_U->reset(ap_rst);
    reshape_output_V_U->address0(reshape_output_V_address0);
    reshape_output_V_U->ce0(reshape_output_V_ce0);
    reshape_output_V_U->we0(reshape_output_V_we0);
    reshape_output_V_U->d0(grp_reshape_fu_288_output_V_d0);
    reshape_output_V_U->q0(reshape_output_V_q0);
    grp_perform_conv_1_fu_258 = new perform_conv_1("grp_perform_conv_1_fu_258");
    grp_perform_conv_1_fu_258->ap_clk(ap_clk);
    grp_perform_conv_1_fu_258->ap_rst(ap_rst);
    grp_perform_conv_1_fu_258->ap_start(grp_perform_conv_1_fu_258_ap_start);
    grp_perform_conv_1_fu_258->ap_done(grp_perform_conv_1_fu_258_ap_done);
    grp_perform_conv_1_fu_258->ap_idle(grp_perform_conv_1_fu_258_ap_idle);
    grp_perform_conv_1_fu_258->ap_ready(grp_perform_conv_1_fu_258_ap_ready);
    grp_perform_conv_1_fu_258->input_V_address0(grp_perform_conv_1_fu_258_input_V_address0);
    grp_perform_conv_1_fu_258->input_V_ce0(grp_perform_conv_1_fu_258_input_V_ce0);
    grp_perform_conv_1_fu_258->input_V_q0(mem_conv1_0_V_q0);
    grp_perform_conv_1_fu_258->input_V_address1(grp_perform_conv_1_fu_258_input_V_address1);
    grp_perform_conv_1_fu_258->input_V_ce1(grp_perform_conv_1_fu_258_input_V_ce1);
    grp_perform_conv_1_fu_258->input_V_q1(mem_conv1_0_V_q1);
    grp_perform_conv_1_fu_258->input_V1_address0(grp_perform_conv_1_fu_258_input_V1_address0);
    grp_perform_conv_1_fu_258->input_V1_ce0(grp_perform_conv_1_fu_258_input_V1_ce0);
    grp_perform_conv_1_fu_258->input_V1_q0(mem_conv1_1_V_q0);
    grp_perform_conv_1_fu_258->input_V1_address1(grp_perform_conv_1_fu_258_input_V1_address1);
    grp_perform_conv_1_fu_258->input_V1_ce1(grp_perform_conv_1_fu_258_input_V1_ce1);
    grp_perform_conv_1_fu_258->input_V1_q1(mem_conv1_1_V_q1);
    grp_perform_conv_1_fu_258->input_V2_address0(grp_perform_conv_1_fu_258_input_V2_address0);
    grp_perform_conv_1_fu_258->input_V2_ce0(grp_perform_conv_1_fu_258_input_V2_ce0);
    grp_perform_conv_1_fu_258->input_V2_q0(mem_conv1_2_V_q0);
    grp_perform_conv_1_fu_258->input_V2_address1(grp_perform_conv_1_fu_258_input_V2_address1);
    grp_perform_conv_1_fu_258->input_V2_ce1(grp_perform_conv_1_fu_258_input_V2_ce1);
    grp_perform_conv_1_fu_258->input_V2_q1(mem_conv1_2_V_q1);
    grp_perform_conv_1_fu_258->output_V_address0(grp_perform_conv_1_fu_258_output_V_address0);
    grp_perform_conv_1_fu_258->output_V_ce0(grp_perform_conv_1_fu_258_output_V_ce0);
    grp_perform_conv_1_fu_258->output_V_we0(grp_perform_conv_1_fu_258_output_V_we0);
    grp_perform_conv_1_fu_258->output_V_d0(grp_perform_conv_1_fu_258_output_V_d0);
    grp_perform_conv_1_fu_258->output_V_q0(mem_conv2_0_V_q0);
    grp_perform_conv_1_fu_258->output_V3_address0(grp_perform_conv_1_fu_258_output_V3_address0);
    grp_perform_conv_1_fu_258->output_V3_ce0(grp_perform_conv_1_fu_258_output_V3_ce0);
    grp_perform_conv_1_fu_258->output_V3_we0(grp_perform_conv_1_fu_258_output_V3_we0);
    grp_perform_conv_1_fu_258->output_V3_d0(grp_perform_conv_1_fu_258_output_V3_d0);
    grp_perform_conv_1_fu_258->output_V3_q0(mem_conv2_1_V_q0);
    grp_perform_conv_1_fu_258->output_V4_address0(grp_perform_conv_1_fu_258_output_V4_address0);
    grp_perform_conv_1_fu_258->output_V4_ce0(grp_perform_conv_1_fu_258_output_V4_ce0);
    grp_perform_conv_1_fu_258->output_V4_we0(grp_perform_conv_1_fu_258_output_V4_we0);
    grp_perform_conv_1_fu_258->output_V4_d0(grp_perform_conv_1_fu_258_output_V4_d0);
    grp_perform_conv_1_fu_258->output_V4_q0(mem_conv2_2_V_q0);
    grp_perform_conv_1_fu_258->output_V5_address0(grp_perform_conv_1_fu_258_output_V5_address0);
    grp_perform_conv_1_fu_258->output_V5_ce0(grp_perform_conv_1_fu_258_output_V5_ce0);
    grp_perform_conv_1_fu_258->output_V5_we0(grp_perform_conv_1_fu_258_output_V5_we0);
    grp_perform_conv_1_fu_258->output_V5_d0(grp_perform_conv_1_fu_258_output_V5_d0);
    grp_perform_conv_1_fu_258->output_V5_q0(mem_conv2_3_V_q0);
    grp_perform_conv_1_fu_258->output_V6_address0(grp_perform_conv_1_fu_258_output_V6_address0);
    grp_perform_conv_1_fu_258->output_V6_ce0(grp_perform_conv_1_fu_258_output_V6_ce0);
    grp_perform_conv_1_fu_258->output_V6_we0(grp_perform_conv_1_fu_258_output_V6_we0);
    grp_perform_conv_1_fu_258->output_V6_d0(grp_perform_conv_1_fu_258_output_V6_d0);
    grp_perform_conv_1_fu_258->output_V6_q0(mem_conv2_4_V_q0);
    grp_perform_conv_fu_274 = new perform_conv("grp_perform_conv_fu_274");
    grp_perform_conv_fu_274->ap_clk(ap_clk);
    grp_perform_conv_fu_274->ap_rst(ap_rst);
    grp_perform_conv_fu_274->ap_start(grp_perform_conv_fu_274_ap_start);
    grp_perform_conv_fu_274->ap_done(grp_perform_conv_fu_274_ap_done);
    grp_perform_conv_fu_274->ap_idle(grp_perform_conv_fu_274_ap_idle);
    grp_perform_conv_fu_274->ap_ready(grp_perform_conv_fu_274_ap_ready);
    grp_perform_conv_fu_274->input_0_V_address0(grp_perform_conv_fu_274_input_0_V_address0);
    grp_perform_conv_fu_274->input_0_V_ce0(grp_perform_conv_fu_274_input_0_V_ce0);
    grp_perform_conv_fu_274->input_0_V_q0(mem_conv2_0_V_q0);
    grp_perform_conv_fu_274->input_0_V_address1(grp_perform_conv_fu_274_input_0_V_address1);
    grp_perform_conv_fu_274->input_0_V_ce1(grp_perform_conv_fu_274_input_0_V_ce1);
    grp_perform_conv_fu_274->input_0_V_q1(mem_conv2_0_V_q1);
    grp_perform_conv_fu_274->input_1_V_address0(grp_perform_conv_fu_274_input_1_V_address0);
    grp_perform_conv_fu_274->input_1_V_ce0(grp_perform_conv_fu_274_input_1_V_ce0);
    grp_perform_conv_fu_274->input_1_V_q0(mem_conv2_1_V_q0);
    grp_perform_conv_fu_274->input_1_V_address1(grp_perform_conv_fu_274_input_1_V_address1);
    grp_perform_conv_fu_274->input_1_V_ce1(grp_perform_conv_fu_274_input_1_V_ce1);
    grp_perform_conv_fu_274->input_1_V_q1(mem_conv2_1_V_q1);
    grp_perform_conv_fu_274->input_2_V_address0(grp_perform_conv_fu_274_input_2_V_address0);
    grp_perform_conv_fu_274->input_2_V_ce0(grp_perform_conv_fu_274_input_2_V_ce0);
    grp_perform_conv_fu_274->input_2_V_q0(mem_conv2_2_V_q0);
    grp_perform_conv_fu_274->input_2_V_address1(grp_perform_conv_fu_274_input_2_V_address1);
    grp_perform_conv_fu_274->input_2_V_ce1(grp_perform_conv_fu_274_input_2_V_ce1);
    grp_perform_conv_fu_274->input_2_V_q1(mem_conv2_2_V_q1);
    grp_perform_conv_fu_274->input_3_V_address0(grp_perform_conv_fu_274_input_3_V_address0);
    grp_perform_conv_fu_274->input_3_V_ce0(grp_perform_conv_fu_274_input_3_V_ce0);
    grp_perform_conv_fu_274->input_3_V_q0(mem_conv2_3_V_q0);
    grp_perform_conv_fu_274->input_3_V_address1(grp_perform_conv_fu_274_input_3_V_address1);
    grp_perform_conv_fu_274->input_3_V_ce1(grp_perform_conv_fu_274_input_3_V_ce1);
    grp_perform_conv_fu_274->input_3_V_q1(mem_conv2_3_V_q1);
    grp_perform_conv_fu_274->input_4_V_address0(grp_perform_conv_fu_274_input_4_V_address0);
    grp_perform_conv_fu_274->input_4_V_ce0(grp_perform_conv_fu_274_input_4_V_ce0);
    grp_perform_conv_fu_274->input_4_V_q0(mem_conv2_4_V_q0);
    grp_perform_conv_fu_274->input_4_V_address1(grp_perform_conv_fu_274_input_4_V_address1);
    grp_perform_conv_fu_274->input_4_V_ce1(grp_perform_conv_fu_274_input_4_V_ce1);
    grp_perform_conv_fu_274->input_4_V_q1(mem_conv2_4_V_q1);
    grp_perform_conv_fu_274->output_V_address0(grp_perform_conv_fu_274_output_V_address0);
    grp_perform_conv_fu_274->output_V_ce0(grp_perform_conv_fu_274_output_V_ce0);
    grp_perform_conv_fu_274->output_V_we0(grp_perform_conv_fu_274_output_V_we0);
    grp_perform_conv_fu_274->output_V_d0(grp_perform_conv_fu_274_output_V_d0);
    grp_perform_conv_fu_274->output_V_q0(mem_conv3_V_q0);
    grp_reshape_fu_288 = new reshape("grp_reshape_fu_288");
    grp_reshape_fu_288->ap_clk(ap_clk);
    grp_reshape_fu_288->ap_rst(ap_rst);
    grp_reshape_fu_288->ap_start(grp_reshape_fu_288_ap_start);
    grp_reshape_fu_288->ap_done(grp_reshape_fu_288_ap_done);
    grp_reshape_fu_288->ap_idle(grp_reshape_fu_288_ap_idle);
    grp_reshape_fu_288->ap_ready(grp_reshape_fu_288_ap_ready);
    grp_reshape_fu_288->input_V_address0(grp_reshape_fu_288_input_V_address0);
    grp_reshape_fu_288->input_V_ce0(grp_reshape_fu_288_input_V_ce0);
    grp_reshape_fu_288->input_V_q0(mem_conv3_V_q0);
    grp_reshape_fu_288->output_V_address0(grp_reshape_fu_288_output_V_address0);
    grp_reshape_fu_288->output_V_ce0(grp_reshape_fu_288_output_V_ce0);
    grp_reshape_fu_288->output_V_we0(grp_reshape_fu_288_output_V_we0);
    grp_reshape_fu_288->output_V_d0(grp_reshape_fu_288_output_V_d0);
    dut_uitofp_32ns_3Aem_U101 = new dut_uitofp_32ns_3Aem<1,6,32,32>("dut_uitofp_32ns_3Aem_U101");
    dut_uitofp_32ns_3Aem_U101->clk(ap_clk);
    dut_uitofp_32ns_3Aem_U101->reset(ap_rst);
    dut_uitofp_32ns_3Aem_U101->din0(tmp32_V_3_reg_680);
    dut_uitofp_32ns_3Aem_U101->ce(ap_var_for_const0);
    dut_uitofp_32ns_3Aem_U101->dout(grp_fu_294_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond_fu_378_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond_fu_378_p2 );

    SC_METHOD(thread_exitcond5_fu_301_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( bvh_d_index_reg_214 );

    SC_METHOD(thread_exitcond_fu_378_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( i4_reg_247 );

    SC_METHOD(thread_grp_perform_conv_1_fu_258_ap_start);
    sensitive << ( grp_perform_conv_1_fu_258_ap_start_reg );

    SC_METHOD(thread_grp_perform_conv_fu_274_ap_start);
    sensitive << ( grp_perform_conv_fu_274_ap_start_reg );

    SC_METHOD(thread_grp_reshape_fu_288_ap_start);
    sensitive << ( grp_reshape_fu_288_ap_start_reg );

    SC_METHOD(thread_i_3_fu_384_p2);
    sensitive << ( i4_reg_247 );

    SC_METHOD(thread_i_fu_307_p2);
    sensitive << ( bvh_d_index_reg_214 );

    SC_METHOD(thread_icmp_fu_483_p2);
    sensitive << ( tmp_23_reg_654 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( tmp_67_fu_473_p4 );

    SC_METHOD(thread_idx_urem_fu_370_p3);
    sensitive << ( next_urem_fu_358_p2 );
    sensitive << ( tmp_73_fu_364_p2 );

    SC_METHOD(thread_index_assign_cast3_fu_297_p1);
    sensitive << ( bvh_d_index_reg_214 );

    SC_METHOD(thread_mem_conv1_0_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_301_p2 );
    sensitive << ( grp_perform_conv_1_fu_258_input_V_address0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_fu_351_p1 );
    sensitive << ( tmp_62_fu_331_p1 );

    SC_METHOD(thread_mem_conv1_0_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_301_p2 );
    sensitive << ( grp_perform_conv_1_fu_258_input_V_ce0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_62_fu_331_p1 );

    SC_METHOD(thread_mem_conv1_0_V_ce1);
    sensitive << ( grp_perform_conv_1_fu_258_input_V_ce1 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mem_conv1_0_V_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_301_p2 );
    sensitive << ( tmp_62_fu_331_p1 );

    SC_METHOD(thread_mem_conv1_1_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_301_p2 );
    sensitive << ( grp_perform_conv_1_fu_258_input_V1_address0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_fu_351_p1 );
    sensitive << ( tmp_62_fu_331_p1 );

    SC_METHOD(thread_mem_conv1_1_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_301_p2 );
    sensitive << ( grp_perform_conv_1_fu_258_input_V1_ce0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_62_fu_331_p1 );

    SC_METHOD(thread_mem_conv1_1_V_ce1);
    sensitive << ( grp_perform_conv_1_fu_258_input_V1_ce1 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mem_conv1_1_V_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_301_p2 );
    sensitive << ( tmp_62_fu_331_p1 );

    SC_METHOD(thread_mem_conv1_2_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_301_p2 );
    sensitive << ( grp_perform_conv_1_fu_258_input_V2_address0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( newIndex1_fu_351_p1 );
    sensitive << ( tmp_62_fu_331_p1 );

    SC_METHOD(thread_mem_conv1_2_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_301_p2 );
    sensitive << ( grp_perform_conv_1_fu_258_input_V2_ce0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_62_fu_331_p1 );

    SC_METHOD(thread_mem_conv1_2_V_ce1);
    sensitive << ( grp_perform_conv_1_fu_258_input_V2_ce1 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mem_conv1_2_V_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_301_p2 );
    sensitive << ( tmp_62_fu_331_p1 );

    SC_METHOD(thread_mem_conv2_0_V_address0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V_address0 );
    sensitive << ( grp_perform_conv_fu_274_input_0_V_address0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_0_V_ce0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V_ce0 );
    sensitive << ( grp_perform_conv_fu_274_input_0_V_ce0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_0_V_ce1);
    sensitive << ( grp_perform_conv_fu_274_input_0_V_ce1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_0_V_we0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V_we0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mem_conv2_1_V_address0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V3_address0 );
    sensitive << ( grp_perform_conv_fu_274_input_1_V_address0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_1_V_ce0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V3_ce0 );
    sensitive << ( grp_perform_conv_fu_274_input_1_V_ce0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_1_V_ce1);
    sensitive << ( grp_perform_conv_fu_274_input_1_V_ce1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_1_V_we0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V3_we0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mem_conv2_2_V_address0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V4_address0 );
    sensitive << ( grp_perform_conv_fu_274_input_2_V_address0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_2_V_ce0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V4_ce0 );
    sensitive << ( grp_perform_conv_fu_274_input_2_V_ce0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_2_V_ce1);
    sensitive << ( grp_perform_conv_fu_274_input_2_V_ce1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_2_V_we0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V4_we0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mem_conv2_3_V_address0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V5_address0 );
    sensitive << ( grp_perform_conv_fu_274_input_3_V_address0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_3_V_ce0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V5_ce0 );
    sensitive << ( grp_perform_conv_fu_274_input_3_V_ce0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_3_V_ce1);
    sensitive << ( grp_perform_conv_fu_274_input_3_V_ce1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_3_V_we0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V5_we0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mem_conv2_4_V_address0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V6_address0 );
    sensitive << ( grp_perform_conv_fu_274_input_4_V_address0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_4_V_ce0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V6_ce0 );
    sensitive << ( grp_perform_conv_fu_274_input_4_V_ce0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_4_V_ce1);
    sensitive << ( grp_perform_conv_fu_274_input_4_V_ce1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv2_4_V_we0);
    sensitive << ( grp_perform_conv_1_fu_258_output_V6_we0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mem_conv3_V_address0);
    sensitive << ( grp_perform_conv_fu_274_output_V_address0 );
    sensitive << ( grp_reshape_fu_288_input_V_address0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv3_V_ce0);
    sensitive << ( grp_perform_conv_fu_274_output_V_ce0 );
    sensitive << ( grp_reshape_fu_288_input_V_ce0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mem_conv3_V_we0);
    sensitive << ( grp_perform_conv_fu_274_output_V_we0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_msb_idx_1_cast_fu_469_p1);
    sensitive << ( msb_idx_1_fu_463_p3 );

    SC_METHOD(thread_msb_idx_1_fu_463_p3);
    sensitive << ( tmp_65_reg_670 );
    sensitive << ( tmp_66_reg_675 );

    SC_METHOD(thread_msb_idx_fu_445_p2);
    sensitive << ( num_zeros_fu_437_p3 );

    SC_METHOD(thread_newIndex1_fu_351_p1);
    sensitive << ( tmp_63_fu_341_p4 );

    SC_METHOD(thread_next_mul_fu_335_p2);
    sensitive << ( phi_mul_reg_225 );

    SC_METHOD(thread_next_urem_fu_358_p2);
    sensitive << ( phi_urem_reg_236 );

    SC_METHOD(thread_num_zeros_fu_437_p3);
    sensitive << ( p_Result_4_fu_429_p3 );

    SC_METHOD(thread_output_V_address0);
    sensitive << ( tmp_22_reg_631 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_output_V_ce0);
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_output_V_d0);
    sensitive << ( tmp_23_reg_654 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( p_Result_5_fu_578_p5 );

    SC_METHOD(thread_output_V_we0);
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_p_Repl2_2_trunc_fu_565_p2);
    sensitive << ( tmp1_cast_cast_fu_558_p3 );
    sensitive << ( tmp_72_fu_555_p1 );

    SC_METHOD(thread_p_Result_3_fu_419_p4);
    sensitive << ( p_Val2_5_fu_413_p3 );

    SC_METHOD(thread_p_Result_4_fu_429_p3);
    sensitive << ( p_Result_3_fu_419_p4 );

    SC_METHOD(thread_p_Result_5_fu_578_p5);
    sensitive << ( tmp32_V_6_reg_685 );
    sensitive << ( tmp_31_fu_571_p3 );

    SC_METHOD(thread_p_Result_8_fu_539_p4);
    sensitive << ( tmp32_V_6_fu_535_p1 );

    SC_METHOD(thread_p_Result_s_fu_518_p2);
    sensitive << ( p_Val2_5_reg_659 );
    sensitive << ( tmp_70_fu_514_p1 );

    SC_METHOD(thread_p_Val2_5_fu_413_p3);
    sensitive << ( p_Val2_s_reg_641 );
    sensitive << ( is_neg_reg_648 );
    sensitive << ( tmp_24_fu_408_p2 );

    SC_METHOD(thread_reshape_output_V_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_22_fu_390_p1 );
    sensitive << ( grp_reshape_fu_288_output_V_address0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_reshape_output_V_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_reshape_fu_288_output_V_ce0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_reshape_output_V_we0);
    sensitive << ( grp_reshape_fu_288_output_V_we0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_tmp1_cast_cast_fu_558_p3);
    sensitive << ( tmp_29_reg_690 );

    SC_METHOD(thread_tmp32_V_1_fu_498_p2);
    sensitive << ( tmp32_V_fu_489_p1 );
    sensitive << ( tmp_27_fu_492_p2 );

    SC_METHOD(thread_tmp32_V_2_fu_523_p1);
    sensitive << ( p_Result_s_fu_518_p2 );

    SC_METHOD(thread_tmp32_V_3_fu_527_p3);
    sensitive << ( icmp_fu_483_p2 );
    sensitive << ( tmp32_V_1_fu_498_p2 );
    sensitive << ( tmp32_V_2_fu_523_p1 );

    SC_METHOD(thread_tmp32_V_6_fu_535_p1);
    sensitive << ( grp_fu_294_p1 );

    SC_METHOD(thread_tmp32_V_fu_489_p1);
    sensitive << ( p_Val2_5_reg_659 );

    SC_METHOD(thread_tmp_22_fu_390_p1);
    sensitive << ( i4_reg_247 );

    SC_METHOD(thread_tmp_23_fu_403_p2);
    sensitive << ( p_Val2_s_reg_641 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_tmp_24_fu_408_p2);
    sensitive << ( p_Val2_s_reg_641 );

    SC_METHOD(thread_tmp_27_fu_492_p2);
    sensitive << ( msb_idx_1_cast_fu_469_p1 );

    SC_METHOD(thread_tmp_29_fu_549_p2);
    sensitive << ( tmp_23_reg_654 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( p_Result_8_fu_539_p4 );

    SC_METHOD(thread_tmp_31_fu_571_p3);
    sensitive << ( is_neg_reg_648 );
    sensitive << ( p_Repl2_2_trunc_fu_565_p2 );

    SC_METHOD(thread_tmp_62_fu_331_p1);
    sensitive << ( phi_urem_reg_236 );

    SC_METHOD(thread_tmp_63_fu_341_p4);
    sensitive << ( phi_mul_reg_225 );

    SC_METHOD(thread_tmp_65_fu_451_p1);
    sensitive << ( msb_idx_fu_445_p2 );

    SC_METHOD(thread_tmp_67_fu_473_p4);
    sensitive << ( msb_idx_1_fu_463_p3 );

    SC_METHOD(thread_tmp_68_fu_504_p1);
    sensitive << ( msb_idx_1_fu_463_p3 );

    SC_METHOD(thread_tmp_69_fu_508_p2);
    sensitive << ( tmp_68_fu_504_p1 );

    SC_METHOD(thread_tmp_70_fu_514_p1);
    sensitive << ( tmp_69_fu_508_p2 );

    SC_METHOD(thread_tmp_72_fu_555_p1);
    sensitive << ( msb_idx_reg_665 );

    SC_METHOD(thread_tmp_73_fu_364_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_301_p2 );
    sensitive << ( next_urem_fu_358_p2 );

    SC_METHOD(thread_tmp_fu_313_p3);
    sensitive << ( input_V );
    sensitive << ( index_assign_cast3_fu_297_p1 );

    SC_METHOD(thread_tmp_s_fu_320_p3);
    sensitive << ( tmp_fu_313_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_301_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond_fu_378_p2 );
    sensitive << ( grp_perform_conv_1_fu_258_ap_done );
    sensitive << ( grp_perform_conv_fu_274_ap_done );
    sensitive << ( grp_reshape_fu_288_ap_done );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000001";
    grp_perform_conv_1_fu_258_ap_start_reg = SC_LOGIC_0;
    grp_perform_conv_fu_274_ap_start_reg = SC_LOGIC_0;
    grp_reshape_fu_288_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "cnn_xcel_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_V, "(port)input_V");
    sc_trace(mVcdFile, output_V_address0, "(port)output_V_address0");
    sc_trace(mVcdFile, output_V_ce0, "(port)output_V_ce0");
    sc_trace(mVcdFile, output_V_we0, "(port)output_V_we0");
    sc_trace(mVcdFile, output_V_d0, "(port)output_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_307_p2, "i_fu_307_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, next_mul_fu_335_p2, "next_mul_fu_335_p2");
    sc_trace(mVcdFile, exitcond5_fu_301_p2, "exitcond5_fu_301_p2");
    sc_trace(mVcdFile, idx_urem_fu_370_p3, "idx_urem_fu_370_p3");
    sc_trace(mVcdFile, i_3_fu_384_p2, "i_3_fu_384_p2");
    sc_trace(mVcdFile, i_3_reg_626, "i_3_reg_626");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_22_fu_390_p1, "tmp_22_fu_390_p1");
    sc_trace(mVcdFile, tmp_22_reg_631, "tmp_22_reg_631");
    sc_trace(mVcdFile, exitcond_fu_378_p2, "exitcond_fu_378_p2");
    sc_trace(mVcdFile, reshape_output_V_q0, "reshape_output_V_q0");
    sc_trace(mVcdFile, p_Val2_s_reg_641, "p_Val2_s_reg_641");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, is_neg_reg_648, "is_neg_reg_648");
    sc_trace(mVcdFile, tmp_23_fu_403_p2, "tmp_23_fu_403_p2");
    sc_trace(mVcdFile, tmp_23_reg_654, "tmp_23_reg_654");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, p_Val2_5_fu_413_p3, "p_Val2_5_fu_413_p3");
    sc_trace(mVcdFile, p_Val2_5_reg_659, "p_Val2_5_reg_659");
    sc_trace(mVcdFile, msb_idx_fu_445_p2, "msb_idx_fu_445_p2");
    sc_trace(mVcdFile, msb_idx_reg_665, "msb_idx_reg_665");
    sc_trace(mVcdFile, tmp_65_fu_451_p1, "tmp_65_fu_451_p1");
    sc_trace(mVcdFile, tmp_65_reg_670, "tmp_65_reg_670");
    sc_trace(mVcdFile, tmp_66_reg_675, "tmp_66_reg_675");
    sc_trace(mVcdFile, tmp32_V_3_fu_527_p3, "tmp32_V_3_fu_527_p3");
    sc_trace(mVcdFile, tmp32_V_3_reg_680, "tmp32_V_3_reg_680");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, tmp32_V_6_fu_535_p1, "tmp32_V_6_fu_535_p1");
    sc_trace(mVcdFile, tmp32_V_6_reg_685, "tmp32_V_6_reg_685");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, tmp_29_fu_549_p2, "tmp_29_fu_549_p2");
    sc_trace(mVcdFile, tmp_29_reg_690, "tmp_29_reg_690");
    sc_trace(mVcdFile, mem_conv1_0_V_address0, "mem_conv1_0_V_address0");
    sc_trace(mVcdFile, mem_conv1_0_V_ce0, "mem_conv1_0_V_ce0");
    sc_trace(mVcdFile, mem_conv1_0_V_we0, "mem_conv1_0_V_we0");
    sc_trace(mVcdFile, mem_conv1_0_V_q0, "mem_conv1_0_V_q0");
    sc_trace(mVcdFile, mem_conv1_0_V_ce1, "mem_conv1_0_V_ce1");
    sc_trace(mVcdFile, mem_conv1_0_V_q1, "mem_conv1_0_V_q1");
    sc_trace(mVcdFile, mem_conv1_1_V_address0, "mem_conv1_1_V_address0");
    sc_trace(mVcdFile, mem_conv1_1_V_ce0, "mem_conv1_1_V_ce0");
    sc_trace(mVcdFile, mem_conv1_1_V_we0, "mem_conv1_1_V_we0");
    sc_trace(mVcdFile, mem_conv1_1_V_q0, "mem_conv1_1_V_q0");
    sc_trace(mVcdFile, mem_conv1_1_V_ce1, "mem_conv1_1_V_ce1");
    sc_trace(mVcdFile, mem_conv1_1_V_q1, "mem_conv1_1_V_q1");
    sc_trace(mVcdFile, mem_conv1_2_V_address0, "mem_conv1_2_V_address0");
    sc_trace(mVcdFile, mem_conv1_2_V_ce0, "mem_conv1_2_V_ce0");
    sc_trace(mVcdFile, mem_conv1_2_V_we0, "mem_conv1_2_V_we0");
    sc_trace(mVcdFile, mem_conv1_2_V_q0, "mem_conv1_2_V_q0");
    sc_trace(mVcdFile, mem_conv1_2_V_ce1, "mem_conv1_2_V_ce1");
    sc_trace(mVcdFile, mem_conv1_2_V_q1, "mem_conv1_2_V_q1");
    sc_trace(mVcdFile, mem_conv2_0_V_address0, "mem_conv2_0_V_address0");
    sc_trace(mVcdFile, mem_conv2_0_V_ce0, "mem_conv2_0_V_ce0");
    sc_trace(mVcdFile, mem_conv2_0_V_we0, "mem_conv2_0_V_we0");
    sc_trace(mVcdFile, mem_conv2_0_V_q0, "mem_conv2_0_V_q0");
    sc_trace(mVcdFile, mem_conv2_0_V_ce1, "mem_conv2_0_V_ce1");
    sc_trace(mVcdFile, mem_conv2_0_V_q1, "mem_conv2_0_V_q1");
    sc_trace(mVcdFile, mem_conv2_1_V_address0, "mem_conv2_1_V_address0");
    sc_trace(mVcdFile, mem_conv2_1_V_ce0, "mem_conv2_1_V_ce0");
    sc_trace(mVcdFile, mem_conv2_1_V_we0, "mem_conv2_1_V_we0");
    sc_trace(mVcdFile, mem_conv2_1_V_q0, "mem_conv2_1_V_q0");
    sc_trace(mVcdFile, mem_conv2_1_V_ce1, "mem_conv2_1_V_ce1");
    sc_trace(mVcdFile, mem_conv2_1_V_q1, "mem_conv2_1_V_q1");
    sc_trace(mVcdFile, mem_conv2_2_V_address0, "mem_conv2_2_V_address0");
    sc_trace(mVcdFile, mem_conv2_2_V_ce0, "mem_conv2_2_V_ce0");
    sc_trace(mVcdFile, mem_conv2_2_V_we0, "mem_conv2_2_V_we0");
    sc_trace(mVcdFile, mem_conv2_2_V_q0, "mem_conv2_2_V_q0");
    sc_trace(mVcdFile, mem_conv2_2_V_ce1, "mem_conv2_2_V_ce1");
    sc_trace(mVcdFile, mem_conv2_2_V_q1, "mem_conv2_2_V_q1");
    sc_trace(mVcdFile, mem_conv2_3_V_address0, "mem_conv2_3_V_address0");
    sc_trace(mVcdFile, mem_conv2_3_V_ce0, "mem_conv2_3_V_ce0");
    sc_trace(mVcdFile, mem_conv2_3_V_we0, "mem_conv2_3_V_we0");
    sc_trace(mVcdFile, mem_conv2_3_V_q0, "mem_conv2_3_V_q0");
    sc_trace(mVcdFile, mem_conv2_3_V_ce1, "mem_conv2_3_V_ce1");
    sc_trace(mVcdFile, mem_conv2_3_V_q1, "mem_conv2_3_V_q1");
    sc_trace(mVcdFile, mem_conv2_4_V_address0, "mem_conv2_4_V_address0");
    sc_trace(mVcdFile, mem_conv2_4_V_ce0, "mem_conv2_4_V_ce0");
    sc_trace(mVcdFile, mem_conv2_4_V_we0, "mem_conv2_4_V_we0");
    sc_trace(mVcdFile, mem_conv2_4_V_q0, "mem_conv2_4_V_q0");
    sc_trace(mVcdFile, mem_conv2_4_V_ce1, "mem_conv2_4_V_ce1");
    sc_trace(mVcdFile, mem_conv2_4_V_q1, "mem_conv2_4_V_q1");
    sc_trace(mVcdFile, mem_conv3_V_address0, "mem_conv3_V_address0");
    sc_trace(mVcdFile, mem_conv3_V_ce0, "mem_conv3_V_ce0");
    sc_trace(mVcdFile, mem_conv3_V_we0, "mem_conv3_V_we0");
    sc_trace(mVcdFile, mem_conv3_V_q0, "mem_conv3_V_q0");
    sc_trace(mVcdFile, reshape_output_V_address0, "reshape_output_V_address0");
    sc_trace(mVcdFile, reshape_output_V_ce0, "reshape_output_V_ce0");
    sc_trace(mVcdFile, reshape_output_V_we0, "reshape_output_V_we0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_ap_start, "grp_perform_conv_1_fu_258_ap_start");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_ap_done, "grp_perform_conv_1_fu_258_ap_done");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_ap_idle, "grp_perform_conv_1_fu_258_ap_idle");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_ap_ready, "grp_perform_conv_1_fu_258_ap_ready");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_input_V_address0, "grp_perform_conv_1_fu_258_input_V_address0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_input_V_ce0, "grp_perform_conv_1_fu_258_input_V_ce0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_input_V_address1, "grp_perform_conv_1_fu_258_input_V_address1");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_input_V_ce1, "grp_perform_conv_1_fu_258_input_V_ce1");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_input_V1_address0, "grp_perform_conv_1_fu_258_input_V1_address0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_input_V1_ce0, "grp_perform_conv_1_fu_258_input_V1_ce0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_input_V1_address1, "grp_perform_conv_1_fu_258_input_V1_address1");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_input_V1_ce1, "grp_perform_conv_1_fu_258_input_V1_ce1");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_input_V2_address0, "grp_perform_conv_1_fu_258_input_V2_address0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_input_V2_ce0, "grp_perform_conv_1_fu_258_input_V2_ce0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_input_V2_address1, "grp_perform_conv_1_fu_258_input_V2_address1");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_input_V2_ce1, "grp_perform_conv_1_fu_258_input_V2_ce1");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V_address0, "grp_perform_conv_1_fu_258_output_V_address0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V_ce0, "grp_perform_conv_1_fu_258_output_V_ce0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V_we0, "grp_perform_conv_1_fu_258_output_V_we0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V_d0, "grp_perform_conv_1_fu_258_output_V_d0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V3_address0, "grp_perform_conv_1_fu_258_output_V3_address0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V3_ce0, "grp_perform_conv_1_fu_258_output_V3_ce0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V3_we0, "grp_perform_conv_1_fu_258_output_V3_we0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V3_d0, "grp_perform_conv_1_fu_258_output_V3_d0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V4_address0, "grp_perform_conv_1_fu_258_output_V4_address0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V4_ce0, "grp_perform_conv_1_fu_258_output_V4_ce0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V4_we0, "grp_perform_conv_1_fu_258_output_V4_we0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V4_d0, "grp_perform_conv_1_fu_258_output_V4_d0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V5_address0, "grp_perform_conv_1_fu_258_output_V5_address0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V5_ce0, "grp_perform_conv_1_fu_258_output_V5_ce0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V5_we0, "grp_perform_conv_1_fu_258_output_V5_we0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V5_d0, "grp_perform_conv_1_fu_258_output_V5_d0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V6_address0, "grp_perform_conv_1_fu_258_output_V6_address0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V6_ce0, "grp_perform_conv_1_fu_258_output_V6_ce0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V6_we0, "grp_perform_conv_1_fu_258_output_V6_we0");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_output_V6_d0, "grp_perform_conv_1_fu_258_output_V6_d0");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_ap_start, "grp_perform_conv_fu_274_ap_start");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_ap_done, "grp_perform_conv_fu_274_ap_done");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_ap_idle, "grp_perform_conv_fu_274_ap_idle");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_ap_ready, "grp_perform_conv_fu_274_ap_ready");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_0_V_address0, "grp_perform_conv_fu_274_input_0_V_address0");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_0_V_ce0, "grp_perform_conv_fu_274_input_0_V_ce0");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_0_V_address1, "grp_perform_conv_fu_274_input_0_V_address1");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_0_V_ce1, "grp_perform_conv_fu_274_input_0_V_ce1");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_1_V_address0, "grp_perform_conv_fu_274_input_1_V_address0");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_1_V_ce0, "grp_perform_conv_fu_274_input_1_V_ce0");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_1_V_address1, "grp_perform_conv_fu_274_input_1_V_address1");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_1_V_ce1, "grp_perform_conv_fu_274_input_1_V_ce1");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_2_V_address0, "grp_perform_conv_fu_274_input_2_V_address0");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_2_V_ce0, "grp_perform_conv_fu_274_input_2_V_ce0");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_2_V_address1, "grp_perform_conv_fu_274_input_2_V_address1");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_2_V_ce1, "grp_perform_conv_fu_274_input_2_V_ce1");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_3_V_address0, "grp_perform_conv_fu_274_input_3_V_address0");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_3_V_ce0, "grp_perform_conv_fu_274_input_3_V_ce0");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_3_V_address1, "grp_perform_conv_fu_274_input_3_V_address1");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_3_V_ce1, "grp_perform_conv_fu_274_input_3_V_ce1");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_4_V_address0, "grp_perform_conv_fu_274_input_4_V_address0");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_4_V_ce0, "grp_perform_conv_fu_274_input_4_V_ce0");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_4_V_address1, "grp_perform_conv_fu_274_input_4_V_address1");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_input_4_V_ce1, "grp_perform_conv_fu_274_input_4_V_ce1");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_output_V_address0, "grp_perform_conv_fu_274_output_V_address0");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_output_V_ce0, "grp_perform_conv_fu_274_output_V_ce0");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_output_V_we0, "grp_perform_conv_fu_274_output_V_we0");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_output_V_d0, "grp_perform_conv_fu_274_output_V_d0");
    sc_trace(mVcdFile, grp_reshape_fu_288_ap_start, "grp_reshape_fu_288_ap_start");
    sc_trace(mVcdFile, grp_reshape_fu_288_ap_done, "grp_reshape_fu_288_ap_done");
    sc_trace(mVcdFile, grp_reshape_fu_288_ap_idle, "grp_reshape_fu_288_ap_idle");
    sc_trace(mVcdFile, grp_reshape_fu_288_ap_ready, "grp_reshape_fu_288_ap_ready");
    sc_trace(mVcdFile, grp_reshape_fu_288_input_V_address0, "grp_reshape_fu_288_input_V_address0");
    sc_trace(mVcdFile, grp_reshape_fu_288_input_V_ce0, "grp_reshape_fu_288_input_V_ce0");
    sc_trace(mVcdFile, grp_reshape_fu_288_output_V_address0, "grp_reshape_fu_288_output_V_address0");
    sc_trace(mVcdFile, grp_reshape_fu_288_output_V_ce0, "grp_reshape_fu_288_output_V_ce0");
    sc_trace(mVcdFile, grp_reshape_fu_288_output_V_we0, "grp_reshape_fu_288_output_V_we0");
    sc_trace(mVcdFile, grp_reshape_fu_288_output_V_d0, "grp_reshape_fu_288_output_V_d0");
    sc_trace(mVcdFile, bvh_d_index_reg_214, "bvh_d_index_reg_214");
    sc_trace(mVcdFile, phi_mul_reg_225, "phi_mul_reg_225");
    sc_trace(mVcdFile, phi_urem_reg_236, "phi_urem_reg_236");
    sc_trace(mVcdFile, i4_reg_247, "i4_reg_247");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, grp_perform_conv_1_fu_258_ap_start_reg, "grp_perform_conv_1_fu_258_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, grp_perform_conv_fu_274_ap_start_reg, "grp_perform_conv_fu_274_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, grp_reshape_fu_288_ap_start_reg, "grp_reshape_fu_288_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, newIndex1_fu_351_p1, "newIndex1_fu_351_p1");
    sc_trace(mVcdFile, tmp_62_fu_331_p1, "tmp_62_fu_331_p1");
    sc_trace(mVcdFile, tmp_s_fu_320_p3, "tmp_s_fu_320_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, index_assign_cast3_fu_297_p1, "index_assign_cast3_fu_297_p1");
    sc_trace(mVcdFile, tmp_fu_313_p3, "tmp_fu_313_p3");
    sc_trace(mVcdFile, tmp_63_fu_341_p4, "tmp_63_fu_341_p4");
    sc_trace(mVcdFile, next_urem_fu_358_p2, "next_urem_fu_358_p2");
    sc_trace(mVcdFile, tmp_73_fu_364_p2, "tmp_73_fu_364_p2");
    sc_trace(mVcdFile, tmp_24_fu_408_p2, "tmp_24_fu_408_p2");
    sc_trace(mVcdFile, p_Result_3_fu_419_p4, "p_Result_3_fu_419_p4");
    sc_trace(mVcdFile, p_Result_4_fu_429_p3, "p_Result_4_fu_429_p3");
    sc_trace(mVcdFile, num_zeros_fu_437_p3, "num_zeros_fu_437_p3");
    sc_trace(mVcdFile, msb_idx_1_fu_463_p3, "msb_idx_1_fu_463_p3");
    sc_trace(mVcdFile, tmp_67_fu_473_p4, "tmp_67_fu_473_p4");
    sc_trace(mVcdFile, msb_idx_1_cast_fu_469_p1, "msb_idx_1_cast_fu_469_p1");
    sc_trace(mVcdFile, tmp32_V_fu_489_p1, "tmp32_V_fu_489_p1");
    sc_trace(mVcdFile, tmp_27_fu_492_p2, "tmp_27_fu_492_p2");
    sc_trace(mVcdFile, tmp_68_fu_504_p1, "tmp_68_fu_504_p1");
    sc_trace(mVcdFile, tmp_69_fu_508_p2, "tmp_69_fu_508_p2");
    sc_trace(mVcdFile, tmp_70_fu_514_p1, "tmp_70_fu_514_p1");
    sc_trace(mVcdFile, p_Result_s_fu_518_p2, "p_Result_s_fu_518_p2");
    sc_trace(mVcdFile, icmp_fu_483_p2, "icmp_fu_483_p2");
    sc_trace(mVcdFile, tmp32_V_1_fu_498_p2, "tmp32_V_1_fu_498_p2");
    sc_trace(mVcdFile, tmp32_V_2_fu_523_p1, "tmp32_V_2_fu_523_p1");
    sc_trace(mVcdFile, grp_fu_294_p1, "grp_fu_294_p1");
    sc_trace(mVcdFile, p_Result_8_fu_539_p4, "p_Result_8_fu_539_p4");
    sc_trace(mVcdFile, tmp1_cast_cast_fu_558_p3, "tmp1_cast_cast_fu_558_p3");
    sc_trace(mVcdFile, tmp_72_fu_555_p1, "tmp_72_fu_555_p1");
    sc_trace(mVcdFile, p_Repl2_2_trunc_fu_565_p2, "p_Repl2_2_trunc_fu_565_p2");
    sc_trace(mVcdFile, tmp_31_fu_571_p3, "tmp_31_fu_571_p3");
    sc_trace(mVcdFile, p_Result_5_fu_578_p5, "p_Result_5_fu_578_p5");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

cnn_xcel::~cnn_xcel() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete mem_conv1_0_V_U;
    delete mem_conv1_1_V_U;
    delete mem_conv1_2_V_U;
    delete mem_conv2_0_V_U;
    delete mem_conv2_1_V_U;
    delete mem_conv2_2_V_U;
    delete mem_conv2_3_V_U;
    delete mem_conv2_4_V_U;
    delete mem_conv3_V_U;
    delete reshape_output_V_U;
    delete grp_perform_conv_1_fu_258;
    delete grp_perform_conv_fu_274;
    delete grp_reshape_fu_288;
    delete dut_uitofp_32ns_3Aem_U101;
}

void cnn_xcel::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void cnn_xcel::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        bvh_d_index_reg_214 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(exitcond5_fu_301_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        bvh_d_index_reg_214 = i_fu_307_p2.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_perform_conv_1_fu_258_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(exitcond5_fu_301_p2.read(), ap_const_lv1_1) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            grp_perform_conv_1_fu_258_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_perform_conv_1_fu_258_ap_ready.read())) {
            grp_perform_conv_1_fu_258_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_perform_conv_fu_274_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            grp_perform_conv_fu_274_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_perform_conv_fu_274_ap_ready.read())) {
            grp_perform_conv_fu_274_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_reshape_fu_288_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_reshape_fu_288_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_reshape_fu_288_ap_ready.read())) {
            grp_reshape_fu_288_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        i4_reg_247 = i_3_reg_626.read();
    } else if ((esl_seteq<1,1,1>(grp_reshape_fu_288_ap_done.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        i4_reg_247 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        phi_mul_reg_225 = ap_const_lv13_0;
    } else if ((esl_seteq<1,1,1>(exitcond5_fu_301_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        phi_mul_reg_225 = next_mul_fu_335_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        phi_urem_reg_236 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(exitcond5_fu_301_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        phi_urem_reg_236 = idx_urem_fu_370_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_3_reg_626 = i_3_fu_384_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        is_neg_reg_648 = reshape_output_V_q0.read().range(13, 13);
        p_Val2_s_reg_641 = reshape_output_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        msb_idx_reg_665 = msb_idx_fu_445_p2.read();
        p_Val2_5_reg_659 = p_Val2_5_fu_413_p3.read();
        tmp_23_reg_654 = tmp_23_fu_403_p2.read();
        tmp_65_reg_670 = tmp_65_fu_451_p1.read();
        tmp_66_reg_675 = msb_idx_fu_445_p2.read().range(31, 31);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_reg_654.read()))) {
        tmp32_V_3_reg_680 = tmp32_V_3_fu_527_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_reg_654.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        tmp32_V_6_reg_685 = tmp32_V_6_fu_535_p1.read();
        tmp_29_reg_690 = tmp_29_fu_549_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_378_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        tmp_22_reg_631 = tmp_22_fu_390_p1.read();
    }
}

void cnn_xcel::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void cnn_xcel::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void cnn_xcel::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void cnn_xcel::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void cnn_xcel::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void cnn_xcel::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void cnn_xcel::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void cnn_xcel::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void cnn_xcel::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void cnn_xcel::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void cnn_xcel::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void cnn_xcel::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void cnn_xcel::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void cnn_xcel::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void cnn_xcel::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(exitcond_fu_378_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void cnn_xcel::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void cnn_xcel::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(exitcond_fu_378_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void cnn_xcel::thread_exitcond5_fu_301_p2() {
    exitcond5_fu_301_p2 = (!bvh_d_index_reg_214.read().is_01() || !ap_const_lv6_31.is_01())? sc_lv<1>(): sc_lv<1>(bvh_d_index_reg_214.read() == ap_const_lv6_31);
}

void cnn_xcel::thread_exitcond_fu_378_p2() {
    exitcond_fu_378_p2 = (!i4_reg_247.read().is_01() || !ap_const_lv10_240.is_01())? sc_lv<1>(): sc_lv<1>(i4_reg_247.read() == ap_const_lv10_240);
}

void cnn_xcel::thread_grp_perform_conv_1_fu_258_ap_start() {
    grp_perform_conv_1_fu_258_ap_start = grp_perform_conv_1_fu_258_ap_start_reg.read();
}

void cnn_xcel::thread_grp_perform_conv_fu_274_ap_start() {
    grp_perform_conv_fu_274_ap_start = grp_perform_conv_fu_274_ap_start_reg.read();
}

void cnn_xcel::thread_grp_reshape_fu_288_ap_start() {
    grp_reshape_fu_288_ap_start = grp_reshape_fu_288_ap_start_reg.read();
}

void cnn_xcel::thread_i_3_fu_384_p2() {
    i_3_fu_384_p2 = (!i4_reg_247.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(i4_reg_247.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void cnn_xcel::thread_i_fu_307_p2() {
    i_fu_307_p2 = (!bvh_d_index_reg_214.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(bvh_d_index_reg_214.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void cnn_xcel::thread_icmp_fu_483_p2() {
    icmp_fu_483_p2 = (!tmp_67_fu_473_p4.read().is_01() || !ap_const_lv26_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_67_fu_473_p4.read() == ap_const_lv26_0);
}

void cnn_xcel::thread_idx_urem_fu_370_p3() {
    idx_urem_fu_370_p3 = (!tmp_73_fu_364_p2.read()[0].is_01())? sc_lv<6>(): ((tmp_73_fu_364_p2.read()[0].to_bool())? next_urem_fu_358_p2.read(): ap_const_lv6_0);
}

void cnn_xcel::thread_index_assign_cast3_fu_297_p1() {
    index_assign_cast3_fu_297_p1 = esl_zext<32,6>(bvh_d_index_reg_214.read());
}

void cnn_xcel::thread_mem_conv1_0_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_301_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(tmp_62_fu_331_p1.read(), ap_const_lv3_0))) {
        mem_conv1_0_V_address0 =  (sc_lv<9>) (newIndex1_fu_351_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv1_0_V_address0 = grp_perform_conv_1_fu_258_input_V_address0.read();
    } else {
        mem_conv1_0_V_address0 = "XXXXXXXXX";
    }
}

void cnn_xcel::thread_mem_conv1_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_301_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(tmp_62_fu_331_p1.read(), ap_const_lv3_0))) {
        mem_conv1_0_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv1_0_V_ce0 = grp_perform_conv_1_fu_258_input_V_ce0.read();
    } else {
        mem_conv1_0_V_ce0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv1_0_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv1_0_V_ce1 = grp_perform_conv_1_fu_258_input_V_ce1.read();
    } else {
        mem_conv1_0_V_ce1 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv1_0_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_301_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(tmp_62_fu_331_p1.read(), ap_const_lv3_0))) {
        mem_conv1_0_V_we0 = ap_const_logic_1;
    } else {
        mem_conv1_0_V_we0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv1_1_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_301_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(tmp_62_fu_331_p1.read(), ap_const_lv3_1))) {
        mem_conv1_1_V_address0 =  (sc_lv<9>) (newIndex1_fu_351_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv1_1_V_address0 = grp_perform_conv_1_fu_258_input_V1_address0.read();
    } else {
        mem_conv1_1_V_address0 = "XXXXXXXXX";
    }
}

void cnn_xcel::thread_mem_conv1_1_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_301_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(tmp_62_fu_331_p1.read(), ap_const_lv3_1))) {
        mem_conv1_1_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv1_1_V_ce0 = grp_perform_conv_1_fu_258_input_V1_ce0.read();
    } else {
        mem_conv1_1_V_ce0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv1_1_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv1_1_V_ce1 = grp_perform_conv_1_fu_258_input_V1_ce1.read();
    } else {
        mem_conv1_1_V_ce1 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv1_1_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_301_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(tmp_62_fu_331_p1.read(), ap_const_lv3_1))) {
        mem_conv1_1_V_we0 = ap_const_logic_1;
    } else {
        mem_conv1_1_V_we0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv1_2_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_301_p2.read(), ap_const_lv1_0) && 
         !esl_seteq<1,3,3>(tmp_62_fu_331_p1.read(), ap_const_lv3_0) && 
         !esl_seteq<1,3,3>(tmp_62_fu_331_p1.read(), ap_const_lv3_1))) {
        mem_conv1_2_V_address0 =  (sc_lv<9>) (newIndex1_fu_351_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv1_2_V_address0 = grp_perform_conv_1_fu_258_input_V2_address0.read();
    } else {
        mem_conv1_2_V_address0 = "XXXXXXXXX";
    }
}

void cnn_xcel::thread_mem_conv1_2_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_301_p2.read(), ap_const_lv1_0) && 
         !esl_seteq<1,3,3>(tmp_62_fu_331_p1.read(), ap_const_lv3_0) && 
         !esl_seteq<1,3,3>(tmp_62_fu_331_p1.read(), ap_const_lv3_1))) {
        mem_conv1_2_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv1_2_V_ce0 = grp_perform_conv_1_fu_258_input_V2_ce0.read();
    } else {
        mem_conv1_2_V_ce0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv1_2_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv1_2_V_ce1 = grp_perform_conv_1_fu_258_input_V2_ce1.read();
    } else {
        mem_conv1_2_V_ce1 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv1_2_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_301_p2.read(), ap_const_lv1_0) && 
         !esl_seteq<1,3,3>(tmp_62_fu_331_p1.read(), ap_const_lv3_0) && 
         !esl_seteq<1,3,3>(tmp_62_fu_331_p1.read(), ap_const_lv3_1))) {
        mem_conv1_2_V_we0 = ap_const_logic_1;
    } else {
        mem_conv1_2_V_we0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_0_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_0_V_address0 = grp_perform_conv_fu_274_input_0_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_0_V_address0 = grp_perform_conv_1_fu_258_output_V_address0.read();
    } else {
        mem_conv2_0_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void cnn_xcel::thread_mem_conv2_0_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_0_V_ce0 = grp_perform_conv_fu_274_input_0_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_0_V_ce0 = grp_perform_conv_1_fu_258_output_V_ce0.read();
    } else {
        mem_conv2_0_V_ce0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_0_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_0_V_ce1 = grp_perform_conv_fu_274_input_0_V_ce1.read();
    } else {
        mem_conv2_0_V_ce1 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_0_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_0_V_we0 = grp_perform_conv_1_fu_258_output_V_we0.read();
    } else {
        mem_conv2_0_V_we0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_1_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_1_V_address0 = grp_perform_conv_fu_274_input_1_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_1_V_address0 = grp_perform_conv_1_fu_258_output_V3_address0.read();
    } else {
        mem_conv2_1_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void cnn_xcel::thread_mem_conv2_1_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_1_V_ce0 = grp_perform_conv_fu_274_input_1_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_1_V_ce0 = grp_perform_conv_1_fu_258_output_V3_ce0.read();
    } else {
        mem_conv2_1_V_ce0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_1_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_1_V_ce1 = grp_perform_conv_fu_274_input_1_V_ce1.read();
    } else {
        mem_conv2_1_V_ce1 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_1_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_1_V_we0 = grp_perform_conv_1_fu_258_output_V3_we0.read();
    } else {
        mem_conv2_1_V_we0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_2_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_2_V_address0 = grp_perform_conv_fu_274_input_2_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_2_V_address0 = grp_perform_conv_1_fu_258_output_V4_address0.read();
    } else {
        mem_conv2_2_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void cnn_xcel::thread_mem_conv2_2_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_2_V_ce0 = grp_perform_conv_fu_274_input_2_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_2_V_ce0 = grp_perform_conv_1_fu_258_output_V4_ce0.read();
    } else {
        mem_conv2_2_V_ce0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_2_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_2_V_ce1 = grp_perform_conv_fu_274_input_2_V_ce1.read();
    } else {
        mem_conv2_2_V_ce1 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_2_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_2_V_we0 = grp_perform_conv_1_fu_258_output_V4_we0.read();
    } else {
        mem_conv2_2_V_we0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_3_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_3_V_address0 = grp_perform_conv_fu_274_input_3_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_3_V_address0 = grp_perform_conv_1_fu_258_output_V5_address0.read();
    } else {
        mem_conv2_3_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void cnn_xcel::thread_mem_conv2_3_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_3_V_ce0 = grp_perform_conv_fu_274_input_3_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_3_V_ce0 = grp_perform_conv_1_fu_258_output_V5_ce0.read();
    } else {
        mem_conv2_3_V_ce0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_3_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_3_V_ce1 = grp_perform_conv_fu_274_input_3_V_ce1.read();
    } else {
        mem_conv2_3_V_ce1 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_3_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_3_V_we0 = grp_perform_conv_1_fu_258_output_V5_we0.read();
    } else {
        mem_conv2_3_V_we0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_4_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_4_V_address0 = grp_perform_conv_fu_274_input_4_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_4_V_address0 = grp_perform_conv_1_fu_258_output_V6_address0.read();
    } else {
        mem_conv2_4_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void cnn_xcel::thread_mem_conv2_4_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_4_V_ce0 = grp_perform_conv_fu_274_input_4_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_4_V_ce0 = grp_perform_conv_1_fu_258_output_V6_ce0.read();
    } else {
        mem_conv2_4_V_ce0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_4_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv2_4_V_ce1 = grp_perform_conv_fu_274_input_4_V_ce1.read();
    } else {
        mem_conv2_4_V_ce1 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv2_4_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mem_conv2_4_V_we0 = grp_perform_conv_1_fu_258_output_V6_we0.read();
    } else {
        mem_conv2_4_V_we0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv3_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        mem_conv3_V_address0 = grp_reshape_fu_288_input_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv3_V_address0 = grp_perform_conv_fu_274_output_V_address0.read();
    } else {
        mem_conv3_V_address0 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void cnn_xcel::thread_mem_conv3_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        mem_conv3_V_ce0 = grp_reshape_fu_288_input_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv3_V_ce0 = grp_perform_conv_fu_274_output_V_ce0.read();
    } else {
        mem_conv3_V_ce0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_mem_conv3_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mem_conv3_V_we0 = grp_perform_conv_fu_274_output_V_we0.read();
    } else {
        mem_conv3_V_we0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_msb_idx_1_cast_fu_469_p1() {
    msb_idx_1_cast_fu_469_p1 = esl_zext<32,31>(msb_idx_1_fu_463_p3.read());
}

void cnn_xcel::thread_msb_idx_1_fu_463_p3() {
    msb_idx_1_fu_463_p3 = (!tmp_66_reg_675.read()[0].is_01())? sc_lv<31>(): ((tmp_66_reg_675.read()[0].to_bool())? ap_const_lv31_0: tmp_65_reg_670.read());
}

void cnn_xcel::thread_msb_idx_fu_445_p2() {
    msb_idx_fu_445_p2 = (!ap_const_lv32_D.is_01() || !num_zeros_fu_437_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_D) - sc_biguint<32>(num_zeros_fu_437_p3.read()));
}

void cnn_xcel::thread_newIndex1_fu_351_p1() {
    newIndex1_fu_351_p1 = esl_zext<64,5>(tmp_63_fu_341_p4.read());
}

void cnn_xcel::thread_next_mul_fu_335_p2() {
    next_mul_fu_335_p2 = (!ap_const_lv13_56.is_01() || !phi_mul_reg_225.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_56) + sc_biguint<13>(phi_mul_reg_225.read()));
}

void cnn_xcel::thread_next_urem_fu_358_p2() {
    next_urem_fu_358_p2 = (!phi_urem_reg_236.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(phi_urem_reg_236.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void cnn_xcel::thread_num_zeros_fu_437_p3() {
    num_zeros_fu_437_p3 = esl_cttz<32,32>(p_Result_4_fu_429_p3.read());
}

void cnn_xcel::thread_output_V_address0() {
    output_V_address0 =  (sc_lv<10>) (tmp_22_reg_631.read());
}

void cnn_xcel::thread_output_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        output_V_ce0 = ap_const_logic_1;
    } else {
        output_V_ce0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_output_V_d0() {
    output_V_d0 = (!tmp_23_reg_654.read()[0].is_01())? sc_lv<32>(): ((tmp_23_reg_654.read()[0].to_bool())? ap_const_lv32_0: p_Result_5_fu_578_p5.read());
}

void cnn_xcel::thread_output_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        output_V_we0 = ap_const_logic_1;
    } else {
        output_V_we0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_p_Repl2_2_trunc_fu_565_p2() {
    p_Repl2_2_trunc_fu_565_p2 = (!tmp1_cast_cast_fu_558_p3.read().is_01() || !tmp_72_fu_555_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp1_cast_cast_fu_558_p3.read()) + sc_biguint<8>(tmp_72_fu_555_p1.read()));
}

void cnn_xcel::thread_p_Result_3_fu_419_p4() {
    p_Result_3_fu_419_p4 = p_Val2_5_fu_413_p3.read().range(0, 13);
}

void cnn_xcel::thread_p_Result_4_fu_429_p3() {
    p_Result_4_fu_429_p3 = esl_concat<18,14>(ap_const_lv18_3FFFF, p_Result_3_fu_419_p4.read());
}

void cnn_xcel::thread_p_Result_5_fu_578_p5() {
    p_Result_5_fu_578_p5 = esl_partset<32,32,9,32,32>(tmp32_V_6_reg_685.read(), tmp_31_fu_571_p3.read(), ap_const_lv32_17, ap_const_lv32_1F);
}

void cnn_xcel::thread_p_Result_8_fu_539_p4() {
    p_Result_8_fu_539_p4 = tmp32_V_6_fu_535_p1.read().range(30, 23);
}

void cnn_xcel::thread_p_Result_s_fu_518_p2() {
    p_Result_s_fu_518_p2 = (!tmp_70_fu_514_p1.read().is_01())? sc_lv<14>(): p_Val2_5_reg_659.read() >> (unsigned short)tmp_70_fu_514_p1.read().to_uint();
}

void cnn_xcel::thread_p_Val2_5_fu_413_p3() {
    p_Val2_5_fu_413_p3 = (!is_neg_reg_648.read()[0].is_01())? sc_lv<14>(): ((is_neg_reg_648.read()[0].to_bool())? tmp_24_fu_408_p2.read(): p_Val2_s_reg_641.read());
}

void cnn_xcel::thread_reshape_output_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        reshape_output_V_address0 =  (sc_lv<10>) (tmp_22_fu_390_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        reshape_output_V_address0 = grp_reshape_fu_288_output_V_address0.read();
    } else {
        reshape_output_V_address0 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void cnn_xcel::thread_reshape_output_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        reshape_output_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        reshape_output_V_ce0 = grp_reshape_fu_288_output_V_ce0.read();
    } else {
        reshape_output_V_ce0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_reshape_output_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        reshape_output_V_we0 = grp_reshape_fu_288_output_V_we0.read();
    } else {
        reshape_output_V_we0 = ap_const_logic_0;
    }
}

void cnn_xcel::thread_tmp1_cast_cast_fu_558_p3() {
    tmp1_cast_cast_fu_558_p3 = (!tmp_29_reg_690.read()[0].is_01())? sc_lv<8>(): ((tmp_29_reg_690.read()[0].to_bool())? ap_const_lv8_74: ap_const_lv8_73);
}

void cnn_xcel::thread_tmp32_V_1_fu_498_p2() {
    tmp32_V_1_fu_498_p2 = (!tmp_27_fu_492_p2.read().is_01())? sc_lv<32>(): tmp32_V_fu_489_p1.read() << (unsigned short)tmp_27_fu_492_p2.read().to_uint();
}

void cnn_xcel::thread_tmp32_V_2_fu_523_p1() {
    tmp32_V_2_fu_523_p1 = esl_zext<32,14>(p_Result_s_fu_518_p2.read());
}

void cnn_xcel::thread_tmp32_V_3_fu_527_p3() {
    tmp32_V_3_fu_527_p3 = (!icmp_fu_483_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_fu_483_p2.read()[0].to_bool())? tmp32_V_1_fu_498_p2.read(): tmp32_V_2_fu_523_p1.read());
}

void cnn_xcel::thread_tmp32_V_6_fu_535_p1() {
    tmp32_V_6_fu_535_p1 = grp_fu_294_p1.read();
}

void cnn_xcel::thread_tmp32_V_fu_489_p1() {
    tmp32_V_fu_489_p1 = esl_zext<32,14>(p_Val2_5_reg_659.read());
}

void cnn_xcel::thread_tmp_22_fu_390_p1() {
    tmp_22_fu_390_p1 = esl_zext<64,10>(i4_reg_247.read());
}

void cnn_xcel::thread_tmp_23_fu_403_p2() {
    tmp_23_fu_403_p2 = (!p_Val2_s_reg_641.read().is_01() || !ap_const_lv14_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Val2_s_reg_641.read() == ap_const_lv14_0);
}

void cnn_xcel::thread_tmp_24_fu_408_p2() {
    tmp_24_fu_408_p2 = (!ap_const_lv14_0.is_01() || !p_Val2_s_reg_641.read().is_01())? sc_lv<14>(): (sc_biguint<14>(ap_const_lv14_0) - sc_biguint<14>(p_Val2_s_reg_641.read()));
}

void cnn_xcel::thread_tmp_27_fu_492_p2() {
    tmp_27_fu_492_p2 = (!ap_const_lv32_1F.is_01() || !msb_idx_1_cast_fu_469_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1F) - sc_biguint<32>(msb_idx_1_cast_fu_469_p1.read()));
}

void cnn_xcel::thread_tmp_29_fu_549_p2() {
    tmp_29_fu_549_p2 = (!p_Result_8_fu_539_p4.read().is_01() || !ap_const_lv8_9E.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_8_fu_539_p4.read() != ap_const_lv8_9E);
}

void cnn_xcel::thread_tmp_31_fu_571_p3() {
    tmp_31_fu_571_p3 = esl_concat<1,8>(is_neg_reg_648.read(), p_Repl2_2_trunc_fu_565_p2.read());
}

void cnn_xcel::thread_tmp_62_fu_331_p1() {
    tmp_62_fu_331_p1 = phi_urem_reg_236.read().range(3-1, 0);
}

void cnn_xcel::thread_tmp_63_fu_341_p4() {
    tmp_63_fu_341_p4 = phi_mul_reg_225.read().range(12, 8);
}

void cnn_xcel::thread_tmp_65_fu_451_p1() {
    tmp_65_fu_451_p1 = msb_idx_fu_445_p2.read().range(31-1, 0);
}

void cnn_xcel::thread_tmp_67_fu_473_p4() {
    tmp_67_fu_473_p4 = msb_idx_1_fu_463_p3.read().range(30, 5);
}

void cnn_xcel::thread_tmp_68_fu_504_p1() {
    tmp_68_fu_504_p1 = msb_idx_1_fu_463_p3.read().range(4-1, 0);
}

void cnn_xcel::thread_tmp_69_fu_508_p2() {
    tmp_69_fu_508_p2 = (!ap_const_lv4_1.is_01() || !tmp_68_fu_504_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(tmp_68_fu_504_p1.read()));
}

void cnn_xcel::thread_tmp_70_fu_514_p1() {
    tmp_70_fu_514_p1 = esl_zext<14,4>(tmp_69_fu_508_p2.read());
}

void cnn_xcel::thread_tmp_72_fu_555_p1() {
    tmp_72_fu_555_p1 = msb_idx_reg_665.read().range(8-1, 0);
}

void cnn_xcel::thread_tmp_73_fu_364_p2() {
    tmp_73_fu_364_p2 = (!next_urem_fu_358_p2.read().is_01() || !ap_const_lv6_3.is_01())? sc_lv<1>(): (sc_biguint<6>(next_urem_fu_358_p2.read()) < sc_biguint<6>(ap_const_lv6_3));
}

void cnn_xcel::thread_tmp_fu_313_p3() {
    tmp_fu_313_p3 = (!index_assign_cast3_fu_297_p1.read().is_01() || sc_biguint<32>(index_assign_cast3_fu_297_p1.read()).to_uint() >= 49)? sc_lv<1>(): input_V.read().range(sc_biguint<32>(index_assign_cast3_fu_297_p1.read()).to_uint(), sc_biguint<32>(index_assign_cast3_fu_297_p1.read()).to_uint());
}

void cnn_xcel::thread_tmp_s_fu_320_p3() {
    tmp_s_fu_320_p3 = esl_concat<1,12>(tmp_fu_313_p3.read(), ap_const_lv12_0);
}

void cnn_xcel::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond5_fu_301_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(grp_perform_conv_1_fu_258_ap_done.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(grp_perform_conv_fu_274_ap_done.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(grp_reshape_fu_288_ap_done.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(exitcond_fu_378_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<18>) ("XXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

