# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/xillydemo.xdc

# IP: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_8x2048 || ORIG_REF_NAME==fifo_8x2048} -quiet] -quiet

# IP: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/fifo_32x512/fifo_32x512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_32x512 || ORIG_REF_NAME==fifo_32x512} -quiet] -quiet

# Block Designs: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/vivado_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system || ORIG_REF_NAME==vivado_system} -quiet] -quiet

# IP: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xillybus_lite_0_0_1/vivado_system_xillybus_lite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_xillybus_lite_0_0 || ORIG_REF_NAME==vivado_system_xillybus_lite_0_0} -quiet] -quiet

# IP: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xillybus_ip_0_0_1/vivado_system_xillybus_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_xillybus_ip_0_0 || ORIG_REF_NAME==vivado_system_xillybus_ip_0_0} -quiet] -quiet

# IP: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0_1/vivado_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_processing_system7_0_0 || ORIG_REF_NAME==vivado_system_processing_system7_0_0} -quiet] -quiet

# IP: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_axi_periph_0_1/vivado_system_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==vivado_system_processing_system7_0_axi_periph_0} -quiet] -quiet

# IP: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0_1/vivado_system_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==vivado_system_rst_processing_system7_0_100M_0} -quiet] -quiet

# IP: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xlconcat_0_0_1/vivado_system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_xlconcat_0_0 || ORIG_REF_NAME==vivado_system_xlconcat_0_0} -quiet] -quiet

# IP: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xbar_0_1/vivado_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_xbar_0 || ORIG_REF_NAME==vivado_system_xbar_0} -quiet] -quiet

# IP: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_1_1/vivado_system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_auto_pc_1 || ORIG_REF_NAME==vivado_system_auto_pc_1} -quiet] -quiet

# IP: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_0_1/vivado_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_auto_pc_0 || ORIG_REF_NAME==vivado_system_auto_pc_0} -quiet] -quiet

# IP: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_2_1/vivado_system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_auto_pc_2 || ORIG_REF_NAME==vivado_system_auto_pc_2} -quiet] -quiet

# IP: ip/dut_ap_uitofp_4_no_dsp_32/dut_ap_uitofp_4_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dut_ap_uitofp_4_no_dsp_32 || ORIG_REF_NAME==dut_ap_uitofp_4_no_dsp_32} -quiet] -quiet

# XDC: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0_1/vivado_system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vivado_system_processing_system7_0_0 || ORIG_REF_NAME==vivado_system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0_1/vivado_system_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vivado_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==vivado_system_rst_processing_system7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0_1/vivado_system_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vivado_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==vivado_system_rst_processing_system7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0_1/vivado_system_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xbar_0_1/vivado_system_xbar_0_ooc.xdc

# XDC: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_1_1/vivado_system_auto_pc_1_ooc.xdc

# XDC: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_0_1/vivado_system_auto_pc_0_ooc.xdc

# XDC: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_2_1/vivado_system_auto_pc_2_ooc.xdc

# XDC: /media/adamsmith/Storage/SynologyDrive/ece5775_lab4-master/ecelinux/zedboard_project/vivado-essentials/vivado_system/vivado_system_ooc.xdc
